# Generated by Django 5.2.7

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatcore', '0003_message_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(default=500)),
                ('message', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
