# Generated by Django 5.2.7

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatcore', '0004_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
